from turtle import*
t=Turtle()
def squareshape():
    for i in range(4):
        t.fd(200)
        t.left(90)
w=Screen()
w.title("program")
t.pensize(5)
t.speed(3)
t.color('black','red')
t.begin_fill()
squareshape()
t.right(90)
t.end_fill()
t.color('black','blue')
t.begin_fill()
squareshape()
t.right(90)
t.end_fill()
t.color('black','green')
t.begin_fill()
squareshape()
t.right(90)
t.end_fill()
t.color('black','yellow')
t.begin_fill()
squareshape()
t.right(90)
t.end_fill()
t.right(45)
t.fd(280)
t.bk(560)
t.fd(280)
t.right(90)
t.fd(280)
t.bk(560)
done()