
import turtle as t
t.speed (10)
t.pensize (8)
t.hideturtle ()
t.screensize (500, 500, bg="white")
#Cat face
t.fillcolor ("#00a1e8")
t.begin_fill ()
t.circle (120)
t.end_fill ()
t.pensize (3)
t.fillcolor ("white")
t.begin_fill ()
t.circle (100)
t.end_fill ()
t.pu ()
t.home ()
t.goto (0, 134)
t.pd ()
t.pensize (4)
t.fillcolor ("#ea0014")
t.begin_fill ()
t.circle (18)
t.end_fill ()
t.pu ()
t.goto (7, 155)
t.pensize (2)
t.color ("white", "white")
t.pd ()
t.begin_fill ()
t.circle (4)
t.end_fill ()
t.pu ()
t.goto (-30, 160)
t.pensize (4)
t.pd ()
t.color ("black", "white")
t.begin_fill ()
a=0.4
for i in range (120):
  if 0<= i<30 or 60<i<90:
    a=a + 0.08
    t.lt (3) #turn left 3 degrees
    t.fd (a) #Walk a step forward
  else:
    a=a-0.08
    t.lt (3)
    t.fd (a)
t.end_fill ()
t.pu ()
t.goto (30, 160)
t.pensize (4)
t.pd ()
t.color ("black", "white")
t.begin_fill ()
for i in range (120):
  if 0<= i<30 or 60<i<90:
    a=a + 0.08
    t.lt (3) #turn left 3 degrees
    t.fd (a) #Step forward a
  else:
    a=a-0.08
    t.lt (3)
    t.fd (a)
t.end_fill ()
t.pu ()
t.goto (-38,190)
t.pensize (8)
t.pd ()
t.right (-30)
t.forward (15)
t.right (70)
t.forward (15)
t.pu ()
t.goto (15, 185)
t.pensize (4)
t.pd ()
t.color ("black", "black")
t.begin_fill ()
t.circle (13)
t.end_fill ()
t.pu ()
t.goto (13, 190)
t.pensize (2)
t.pd ()
t.color ("white", "white")
t.begin_fill ()
t.circle (5)
t.end_fill ()
t.pu ()
t.home ()
t.goto (0, 134)
t.pensize (4)
t.pencolor ("black")
t.pd ()
t.right (90)
t.forward (40)
t.pu ()
t.home ()
t.goto (0, 124)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (10)
t.forward (80)
t.pu ()
t.home ()
t.goto (0, 114)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (6)
t.forward (80)
t.pu ()
t.home ()
t.goto (0,104)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (0)
t.forward (80)
#Left beard
t.pu ()
t.home ()
t.goto (0,124)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (170)
t.forward (80)
t.pu ()
t.home ()
t.goto (0, 114)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (174)
t.forward (80)
t.pu ()
t.home ()
t.goto (0, 104)
t.pensize (3)
t.pencolor ("black")
t.pd ()
t.left (180)
t.forward (80)
t.pu ()
t.goto (-70, 70)
t.pd ()
t.color ("black", "red")
t.pensize (6)
t.seth (-60)
t.begin_fill ()
t.circle (80,40)
t.circle (80,80)
t.end_fill ()
t.pu ()
