from turtle import *
import time
time.time()
t=Turtle()
w=Screen()
w.title("simple analog clock")
w.bgcolor('black')
w.setup(600,600)
t.speed(0)
t.pensize(3)
t.hideturtle()
w.tracer(0)
def drow_clock(h,m,s,t):
    t.up()
    t.goto(0,210)
    t.setheading(180)
    t.pencolor('blue')
    t.down()
    t.circle(210)
    #
    t.up()
    t.goto(0,0)
    t.setheading(90)
    for k in range(12):
        t.forward(190)
        t.down()
        t.fd(20)
        t.up()
        t.goto(0,0)
        t.right(30)
     #
    t.up()
    t.goto(0, 0)
    t.setheading(90)
    for k in range(60):
        t.forward(200)
        t.down()
        t.fd(10)
        t.up()
        t.goto(0, 0)
        t.right(6)
    # no
    #one
    t.up()
    t.goto(0,0)
    t.setheading(60)
    t.fd(145)
    t.setheading(0)
    t.fd(15)
    t.write(1,move=False,align="center",font=("arial",25,"normal"))
    # two
    t.up()
    t.goto(0, 0)
    t.setheading(30)
    t.fd(135)
    t.setheading(0)
    t.fd(35)
    t.write(2, move=False, align="center", font=("arial", 25, "normal"))
    # three
    t.up()
    t.goto(0, 0)
    t.setheading(352)
    t.fd(150)
    t.setheading(0)
    t.fd(25)
    t.write(3, move=False, align="center", font=("arial", 25, "normal"))
    # four
    t.up()
    t.goto(0, 0)
    t.setheading(315)
    t.fd(145)
    t.setheading(0)
    t.fd(45)
    t.write(4, move=False, align="center", font=("arial", 25, "normal"))
    # five
    t.up()
    t.goto(0, 0)
    t.setheading(290)
    t.fd(178)
    t.setheading(0)
    t.fd(25)
    t.write(5, move=False, align="center", font=("arial", 25, "normal"))
    # six
    t.up()
    t.goto(0, 0)
    t.setheading(270)
    t.fd(190)
    t.write(6, move=False, align="center", font=("arial", 25, "normal"))
    # seven
    t.up()
    t.goto(0, 0)
    t.setheading(258)
    t.fd(170)
    t.setheading(180)
    t.fd(48)
    t.write(7, move=False, align="center", font=("arial", 25, "normal"))
    # eight
    t.up()
    t.goto(0, 0)
    t.setheading(228)
    t.fd(150)
    t.setheading(180)
    t.fd(45)
    t.write(8, move=False, align="center", font=("arial", 25, "normal"))
    # nine
    t.up()
    t.goto(0, 0)
    t.setheading(188)
    t.fd(150)
    t.setheading(180)
    t.fd(25)
    t.write(9, move=False, align="center", font=("arial", 25, "normal"))
    # ten
    t.up()
    t.goto(0, 0)
    t.setheading(150)
    t.fd(135)
    t.setheading(180)
    t.fd(25)
    t.write(10, move=False, align="center", font=("arial", 25, "normal"))
    # eleven
    t.up()
    t.goto(0, 0)
    t.setheading(120)
    t.fd(145)
    t.setheading(180)
    t.fd(15)
    t.write(11, move=False, align="center", font=("arial", 25, "normal"))
    # twelve
    t.up()
    t.goto(0, 0)
    t.setheading(90)
    t.fd(150)
    t.write(12, move=False, align="center", font=("arial", 25, "normal"))

    #
    t.up()
    t.goto(0,0)
    t.pencolor("red")
    t.setheading(90)
    angle=(h/12)*360
    t.right(angle)
    t.down()
    t.fd(80)
    # min
    t.up()
    t.goto(0, 0)
    t.pencolor("white")
    t.setheading(90)
    angle = (m / 60) * 360
    t.right(angle)
    t.down()
    t.fd(120)
    # second
    t.up()
    t.goto(0, 0)
    t.pencolor("yellow")
    t.setheading(90)
    angle = (s /60) * 360
    t.right(angle)
    t.down()
    t.fd(160)
    #
    t.up()
    t.goto(0,0)
    t.pencolor("gold")
    t.setheading(268)
    t.fd(125)
    t.setheading(0)
    t.fd(5)
    t.write("sapnasinghgkp830@gmail.com", move=False, align="center", font=("arial", 10, "normal"))


while True:
    h=int(time.strftime("%I"))
    m = int(time.strftime("%M"))
    s = int(time.strftime("%S"))
    drow_clock(h,m,s,t)
    w.update()
    time.sleep(1)
    t.clear()
mainloop()
drow_clock(t)